### ISSUE TITLE
Beta - Roadmap

### ISSUE THREAD

**Issue by bodinsamuel** [specfy/specfy#134]
- [ ] **Hide / Show connections and services**
  Currently the stack analyser can be a bit too generous and find things that we don't really care to know.

- [ ] **Tag connections and services**
  This would enable having different Flow versions without modification (e.g: production, staging, proposal, public, private, etc.).
  e.g: with a toggle in the UI to only show a tagged path, or show by default only "production" tag 
  
- [ ] **Flow embed and exports**
  Embed a snapshot a Flow or export it as a PNG

- [ ] **UI polishing**
  The UI has been done over the last months but lacks consistency and could use some polishing.

- [ ] Bug fixing
  It seems there are some bugs, which is astonishing !
